const state={question:null,questionNo:1,revealed:0,stats:loadStats()};
const $=id=>document.getElementById(id); const deg=d=>d*Math.PI/180;
function loadStats(){try{return JSON.parse(localStorage.getItem('fcl-stats'))||{done:0,correct:0,streak:0,best:0}}catch{return{done:0,correct:0,streak:0,best:0}}}
function saveStats(){localStorage.setItem('fcl-stats',JSON.stringify(state.stats));renderStats()}
function fmt(x){return `${x.toFixed(2)} N`} function vec(F,t){return{Fx:F*Math.cos(deg(t)),Fy:F*Math.sin(deg(t))}}
function force(){return Math.round((20+Math.random()*160)/10)*10}
function angle(){const a=[0,30,45,60,90,120,135,150,180,210,225,240,270,300,315,330];return a[Math.floor(Math.random()*a.length)]}
function qName(a){a=((a%360)+360)%360;if(a>0&&a<90)return'第一象限 ↗️（+X,+Y）';if(a>90&&a<180)return'第二象限 ↖️（−X,+Y）';if(a>180&&a<270)return'第三象限 ↙️（−X,−Y）';if(a>270&&a<360)return'第四象限 ↘️（+X,−Y）';if(a===0)return'+X 軸';if(a===90)return'+Y 軸';if(a===180)return'−X 軸';return'−Y 軸'}
function makeQuestion(){const m=$('modeSelect').value;state.revealed=0;if(m==='components'){const F=force(),t=angle();state.question={type:m,F,theta:t,level:F>=120?2:1}}else if(m==='resultant'){const n=2+Math.floor(Math.random()*2);state.question={type:m,forces:Array.from({length:n},()=>({F:force(),theta:angle()})),level:n===3?3:2}}else{state.question={type:'full',forces:[{F:20,theta:0},{F:100,theta:45},{F:50,theta:180},{F:150,theta:225},{F:200,theta:300}],level:3}}renderQuestion();$('inlineAnswer').classList.add('hidden');$('feedback').className='feedback';$('feedback').textContent='';$('nextBtn').disabled=true}
function drawVisual(q){const cx=250,cy=95;const fs=q.type==='components'?[{F:q.F,theta:q.theta}]:q.forces;let s='';fs.forEach((f,i)=>{const L=Math.min(82,f.F*.55),x=cx+L*Math.cos(deg(f.theta)),y=cy-L*Math.sin(deg(f.theta));s+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="${i%2?'#4f46e5':'#334155'}" stroke-width="5" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r="5" fill="#334155"/><text x="${x+7}" y="${y-7}" font-size="14" font-weight="700">${q.type==='components'?'F':'F'+(i+1)}</text>`});return`<svg viewBox="0 0 500 190"><line x1="45" y1="${cy}" x2="455" y2="${cy}" stroke="#94a3b8" stroke-width="2"/><line x1="${cx}" y1="160" x2="${cx}" y2="30" stroke="#94a3b8" stroke-width="2"/><text x="460" y="100" font-size="13">+X</text><text x="257" y="25" font-size="13">+Y</text>${s}</svg>`}
function renderQuestion(){const q=state.question;$('difficultyTag').textContent=`Level ${q.level}`;$('questionNo').textContent=`題目 #${state.questionNo}`;let text='',inputs='';if(q.type==='components'){text=`一個力 F = <b>${q.F} N</b>，方向 θ = <b>${q.theta}°</b>（由 +X 逆時針計）<br>請計算 <b>Fx</b> 同 <b>Fy</b>。`;inputs='<div class="answer-grid"><div class="input-box"><label>Fx（N）</label><input id="ans1" inputmode="decimal" placeholder="例如 70.71"></div><div class="input-box"><label>Fy（N）</label><input id="ans2" inputmode="decimal" placeholder="例如 -86.60"></div></div>'}else if(q.type==='resultant'){const d=q.forces.map((x,i)=>`F${i+1} = ${x.F} N @ ${x.theta}°`).join('、');text=`有 ${q.forces.length} 個力：<br><b>${d}</b><br>求合力大小 <b>R</b> 及方向 <b>θR</b>（0°–360°）。`;inputs='<div class="answer-grid"><div class="input-box"><label>R（N）</label><input id="ans1" inputmode="decimal" placeholder="例如 211.42"></div><div class="input-box"><label>θR（°）</label><input id="ans2" inputmode="decimal" placeholder="例如 279.43"></div></div>'}else{text='綜合題：5 個力同時作用。先求每個力嘅 <b>Fx / Fy</b>，再求 <b>ΣFx、ΣFy</b>，最後求 <b>R</b> 同方向。';inputs='<div class="answer-grid"><div class="input-box"><label>ΣFx（N）</label><input id="ans1" inputmode="decimal"></div><div class="input-box"><label>ΣFy（N）</label><input id="ans2" inputmode="decimal"></div><div class="input-box"><label>R（N）</label><input id="ans3" inputmode="decimal"></div><div class="input-box"><label>θR（°）</label><input id="ans4" inputmode="decimal"></div></div>'}$('questionText').innerHTML=text;$('inputArea').innerHTML=inputs;$('forceVisual').innerHTML=drawVisual(q)}
function answers(){const q=state.question;if(q.type==='components'){const v=vec(q.F,q.theta);return{v:[v.Fx,v.Fy]}}const c=q.forces.map(f=>vec(f.F,f.theta)),sx=c.reduce((s,x)=>s+x.Fx,0),sy=c.reduce((s,x)=>s+x.Fy,0),r=Math.hypot(sx,sy);let a=Math.atan2(sy,sx)*180/Math.PI;if(a<0)a+=360;return{v:q.type==='resultant'?[r,a]:[sx,sy,r,a],c,sx,sy}}
function num(id){const x=$(id)?.value.trim();if(!x)return null;const n=Number(x);return Number.isFinite(n)?n:null}function near(a,b){return a!==null&&Math.abs(a-b)<=.75}
function check(){const A=answers().v,got=A.map((_,i)=>num(`ans${i+1}`));if(got.some(x=>x===null)){setFeedback(false,'先填晒答案先喎 😆');return}const ok=got.every((x,i)=>near(x,A[i]));state.stats.done++;if(ok){state.stats.correct++;state.stats.streak++;state.stats.best=Math.max(state.stats.best,state.stats.streak)}else state.stats.streak=0;saveStats();setFeedback(ok,true?'good':'bad');$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=ok?'🎉 答啱！好嘢，繼續保持！':'🧐 未完全啱。答案已經喺下面，逐步睇一次再做下一題。';$('nextBtn').disabled=false;$('inlineAnswer').classList.remove('hidden');renderAnswer()}
function setFeedback(ok,msg){$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').textContent=msg}
function stepHTML(){const q=state.question,a=answers();let h='';if(q.type==='components'){h+=`<div class="step hidden-step"><h4>Step 1｜判斷方向</h4><p>θ = ${q.theta}° → ${qName(q.theta)}，先決定 Fx、Fy 正負。</p></div><div class="step hidden-step"><h4>Step 2｜Fx</h4><div class="eq">Fx = F cos θ = ${q.F} × cos(${q.theta}°) = ${fmt(a.v[0])}</div></div><div class="step hidden-step"><h4>Step 3｜Fy</h4><div class="eq">Fy = F sin θ = ${q.F} × sin(${q.theta}°) = ${fmt(a.v[1])}</div></div><div class="step hidden-step"><h4>✅ Final Answer</h4><p><b>Fx = ${fmt(a.v[0])}</b>，<b>Fy = ${fmt(a.v[1])}</b></p></div>`}else{const lines=a.c.map((x,i)=>`F${i+1}: Fx = ${fmt(x.Fx)}, Fy = ${fmt(x.Fy)}`).join('<br>');h+=`<div class="step hidden-step"><h4>Step 1｜逐個拆力</h4><p>${lines}</p></div><div class="step hidden-step"><h4>Step 2｜求總和</h4><div class="eq">ΣFx = ${fmt(a.sx)}<br>ΣFy = ${fmt(a.sy)}</div></div><div class="step hidden-step"><h4>Step 3｜求合力</h4><div class="eq">R = √(ΣFx² + ΣFy²) = ${fmt(a.v[q.type==='resultant'?0:2])}</div></div><div class="step hidden-step"><h4>Step 4｜求方向</h4><div class="eq">θR = atan2(ΣFy,ΣFx) → ${(q.type==='resultant'?a.v[1]:a.v[3]).toFixed(2)}°</div></div><div class="step hidden-step"><h4>✅ Final Answer</h4><p>${q.type==='resultant'?`<b>R = ${fmt(a.v[0])}</b><br><b>θR = ${a.v[1].toFixed(2)}°</b>`:`<b>ΣFx = ${fmt(a.v[0])}</b><br><b>ΣFy = ${fmt(a.v[1])}</b><br><b>R = ${fmt(a.v[2])}</b><br><b>θR = ${a.v[3].toFixed(2)}°</b>`}</p></div>`}return h}
function renderAnswer(all=false){if(!state.question)return;$('answerCard').innerHTML=stepHTML()+'<div class="reveal-row"><button id="revealNextBtn" class="primary">➡️ 下一步</button><button id="answerNewBtn" class="secondary">🎲 再出一題</button></div>';const steps=[...document.querySelectorAll('#answerCard .step')];state.revealed=all?steps.length:0;if(all)steps.forEach(s=>s.classList.remove('hidden-step'));$('revealNextBtn').addEventListener('click',()=>{if(state.revealed<steps.length)steps[state.revealed++].classList.remove('hidden-step');$('revealNextBtn').textContent=state.revealed>=steps.length?'✅ 已完成':'➡️ 下一步'});$('answerNewBtn').addEventListener('click',()=>{state.questionNo++;makeQuestion()})}
function renderStats(){$('statDone').textContent=state.stats.done;$('statCorrect').textContent=state.stats.correct;$('statRate').textContent=state.stats.done?`${Math.round(state.stats.correct/state.stats.done*100)}%`:'0%';$('statBest').textContent=state.stats.best;$('streakTop').textContent=state.stats.streak}
function sim(){const F=+$('forceSlider').value,t=+$('angleSlider').value,c=vec(F,t);$('forceOut').textContent=F+' N';$('angleOut').textContent=t+'°';$('fxLive').textContent=fmt(c.Fx);$('fyLive').textContent=fmt(c.Fy);const cx=175,cy=125,L=Math.min(95,F*.45),x=cx+L*Math.cos(deg(t)),y=cy-L*Math.sin(deg(t));$('simSvg').innerHTML=`<svg viewBox="0 0 350 210"><line x1="35" y1="${cy}" x2="325" y2="${cy}" stroke="#a3afbf" stroke-width="2"/><line x1="${cx}" y1="190" x2="${cx}" y2="25" stroke="#a3afbf" stroke-width="2"/><line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#334155" stroke-width="6"/><line x1="${cx}" y1="${cy}" x2="${x}" y2="${cy}" stroke="#4f46e5" stroke-width="4" stroke-dasharray="8 6"/><line x1="${x}" y1="${cy}" x2="${x}" y2="${y}" stroke="#0f766e" stroke-width="4" stroke-dasharray="8 6"/><text x="${Math.min(x+8,315)}" y="${Math.max(y-8,25)}" font-size="14" font-weight="700">F</text><text x="${Math.min(x+8,300)}" y="${cy+22}" font-size="14" font-weight="700">Fx</text><text x="${x+8}" y="${Math.max(y+10,40)}" font-size="14" font-weight="700">Fy</text></svg>`}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active-panel'));b.classList.add('active');$(b.dataset.tab).classList.add('active-panel')}));$('checkBtn').addEventListener('click',check);$('nextBtn').addEventListener('click',()=>{state.questionNo++;makeQuestion()});$('newBtn').addEventListener('click',()=>{state.questionNo++;makeQuestion()});$('modeSelect').addEventListener('change',()=>{state.questionNo=1;makeQuestion()});$('forceSlider').addEventListener('input',sim);$('angleSlider').addEventListener('input',sim);document.querySelectorAll('.quadrant').forEach(b=>b.addEventListener('click',()=>{$('angleSlider').value=b.dataset.angle;sim();$('quadrantTip').textContent=`${b.dataset.angle}° → ${qName(+b.dataset.angle)}`}));$('revealMnemonic').addEventListener('click',()=>$('mnemonicExample').classList.toggle('hidden'));$('showAllInlineBtn').addEventListener('click',()=>renderAnswer(true));$('resetStatsBtn').addEventListener('click',()=>{state.stats={done:0,correct:0,streak:0,best:0};saveStats()});renderStats();sim();makeQuestion();
